/*
 * File: app/view/OuterCenterPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('DesignApp.view.DesignPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.designpanel',

    requires: [
        'DesignApp.view.ModulePanel',
        'DesignApp.view.ScenePanel',
        'Ext.tab.Panel'
    ],

    width: 400,
    layout: 'border',
    margin:'-2 0 0 0',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'modulepanel',
                    region: 'east',
                    collapseMode: 'mini',
                    preventHeader: true
                },
                {
                    xtype: 'scenepanel',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }
});